version: "3"

services:
    mysql:
        image: mysql:5.7
        container_name: mysql.fusionner
        hostname: mysql.fusionner
        restart: always
        volumes:
            - ../data/mysql:/var/lib/mysql
            - ./configuration/mysql:/etc/mysql/conf.d
            - ./init/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fusionner
            MYSQL_USER: fusionner
            MYSQL_PASSWORD: fusionner
        ports:
            - 3306:3306
    
    backend:
        build:
            context: ../backend
            dockerfile: Dockerfile
        image: backend.fusionner
        container_name: backend.fusionner
        hostname: backend.fusionner
        restart: always
        volumes: 
            - /home/portal/website/logs/:/home/portal/website/logs/
        ports:
            - "8080:8080"
        environment:    
            - JAVA_OPTS=-Xmx256M -Dspring.profiles.active=dev -Duser.timezone=GMT+08

