### 1. 创建仓库
POST http://localhost:8081/api/v1/repo
Content-Type: application/json

{
  "name": "test",
  "description": "description",
  "url": "http://test.com/git.xxx.git"
}

### 2. 获取一个仓库
GET http://localhost:8081/api/v1/repo/1
Accept: application/json

###